export const STORAGE_STRATEGY = Symbol('STORAGE_STRATEGY');
export const STORAGE_OPTIONS = Symbol('STORAGE_OPTIONS');
export const STORAGE_WEBHOOK_ADAPTER_AZURE = Symbol("STORAGE_WEBHOOK_ADAPTER_AZURE")
export const UPLOAD_CALLBACK_URL = Symbol("UPLOAD_CALLBACK_URL")

