/**
 * Athena
 * Shared Type library
 * ================================
 * Listing Model — Shared Type System
 * "Note" representation on the marketplace
 * ================================
 */

import { Currency } from "../enums/currency.enum"; import { License } from "../enums/license.enum";
import { Visibility } from "../enums/visibility.enum";
import { ID } from "../common/datatype.common";
import { ListingStatus } from "../enums/listing-status.enum";
import { ContentTypes } from "../enums";
import { PublicUser } from "./user.entity";

export interface ListingItem {
  id: string;
  blobKey?: string | null;
  status: "PENDING" | "READY"
  title: string;
  contentType?: ContentTypes | null
  listingId: ID;
  /**
   * markdown of previews
   */
  preview?: string | null;
  createdAt: string;
  deletedAt?: string;
}

export interface Listing {
  id: ID;
  /** Items in this listing */
  items: ListingItem[]
  ownerId: ID;
  owner?: PublicUser | null;
  title: string;
  description?: string | null;
  /**
   * Summary generated by backend
  * can be used for one page preview
  * Markdown content
  */
  summary: string;
  /**
  * Optional for user to fill
  * Otherwise equal to summary
  */
  preview?: string;

  /**
   * floating number with precision 18 and scale of 2
  */
  price: number;

  currency: Currency;

  license: License;

  /**
   * visibility status of this listing,
   * can be set manual by user.
   * By default this will set as Draft mode,
   * and as status became publish, so do the visibility
   */
  visibility: Visibility;

  /** technical status of the listing
   * it is immutable from user
  * only backend modify this
  */
  status: ListingStatus;

  /**
   * Number of times of successful purchase
  */
  downloads: number;
  rating?: number;


  /**
   * As user add items, this incremented as event processor triggered
  */
  itemsExpectedCount: number;

  /**
   * Number of items ready in this listing
    */
  itemsProcessedCount: number;


  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
  archivedAt?: string | null;
  removedAt?: string | null
}

