
name: Build and Push Athena Website to ACR
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Build and Push
        run: |
          IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/athena-website"
          SHA="${{ github.sha }}"
          API_URL="${{ secrets.API_URL }}"
          STORAGE_URL="${{ secrets.STORAGE_URL }}"
          APP_NAME="Athena"

          docker build --build-arg NEXT_PUBLIC_APP_NAME=$APP_NAME --build-arg NEXT_PUBLIC_STORAGE_URL=$STORAGE_URL --build-arg NEXT_PUBLIC_API_URL=$API_URL -t $IMAGE:$SHA -f apps/athena-website/Dockerfile .
          docker push $IMAGE:$SHA

          docker tag $IMAGE:$SHA $IMAGE:latest
          docker push $IMAGE:latest
