name: Deploy Athena Server to ACR

on:
  push:
    branches:
      - main
    
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/athena-server
          SHA=${{github.sha}}
          docker build -t $IMAGE:$SHA -f apps/athena-server/Dockerfile .
          docker push $IMAGE:$SHA
          docker tag $IMGAE:$SHA $IMAGE:latest
          docker push $IMAGE:latest
