
name: Build and Push Athena Website to ACR
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Build and Push
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/athena-website
          SHA=${{github.sha}}
          docker build -t $IMAGE:$SHA -f apps/athena-website/Dockerfile .
          docker push $IMAGE:$SHA
          docker tag $IMGAE:$SHA $IMAGE:latest
          docker push $IMAGE:latest
